-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 10:36:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema control_de_hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema control_de_hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control_de_hotel` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `control_de_hotel` ;

-- -----------------------------------------------------
-- Table `control_de_hotel`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_de_hotel`.`reservas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_entrada` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `forma_pago` VARCHAR(35) NOT NULL,
  `tipo_habitacion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `control_de_hotel`.`huespedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_de_hotel`.`huespedes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_reserva` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `nacionalidad` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_reserva` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `huespedes_ibfk_1`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `control_de_hotel`.`reservas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `control_de_hotel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_de_hotel`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
